### PR TITLE
use_branding patch

### PR DESCRIPTION
**Pull request by dogwolf**
These patch is related to the issue #4
If you set USE_BRANDING = 1 the building process cannot finish because of this line

start "windeployqt" /B /wait windeployqt.exe --%WINDEPLOYQT_BUILD_TYPE% --compiler-runtime "%MY_INSTALL_PATH%/bin/%APP_NAME%.exe" --dir "%MY_QT_DEPLOYMENT_PATH%/"

This %APP_NAME%.exe is not found.
The pull request rename files and directories after the compilation process. The main disadvantage is

nextcloud.cfg and nextcloudsync.dll cannot be rebranded otherwise the nextcloud.exe (the new one rebranded) cannot find the dll and cfg

### CODE REVIEW

**Comment by rwese** [comment]
hi @dogwolf I will try to review this since I need the same change.

In the meantime could you fix the [DCO check](https://github.com/nextcloud/client-building/pull/23/checks?check_run_id=730102679)?

**Comment by dogwolf** [comment]
Hello,
I fix the DCO check.
Sorry about the  patch branch .. I didn't think about that

**Comment by rwese** [comment]
Right now you have also commits other than yours, @dogwolf could you please create a separate branch based off of master with only your commits and update this MergeRequest?

**Comment by rwese** [comment]
@dogwolf, I'Ve tested your PR Changes, you missed one thing in the nextcloud.nsi where it still fails. https://github.com/nextcloud/client-building/blob/e1b925712efd3257f36d6a1c7cbd880115c243f4/nextcloud.nsi#L64

Can you fix this plus use a clean branch?

**Comment by dogwolf** [comment]
Sorry to reply so late, but I'm not used to work with branches.
It took me a while to create a new branch and sent a new PR.
Hope to have sent the patch in the correct way

Thank you

**Comment by rwese** [comment]
Thank you this one can be closed in favor of #30

**Pull request closed without merging**
